### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by danielnovello** [muhannad0/mikrotik-traffic-counter#1]
Hi there

Just checking out this tool and found some issues.
`PHP Notice:  Use of undefined constant id - assumed 'id' in /mikrotik/index.php on line 6`
Returns blank page

Daniel

**Comment by muhannad0** [comment]
Hey Daniel,

Thanks for pointing out the error. In PHP have to declare strings in quotes ' '. Otherwise PHP assumes they're constants. Should be fixed now.

As for returning a blank page, it's because there are no devices added to the db yet. I've added a check to show a message if there are no devices. Configure and run the mikrotik script a few times to see the data.

Muhannad

**Comment by danielnovello** [comment]
Cool
Yes, I actually added the quotes and the errors went away already.
The script does need to run a few times to get some data in the DB.
All good

Daniel
