### ISSUE TITLE
How change to linechart?

### ISSUE THREAD

**Issue by wiratmoko1708** [muhannad0/mikrotik-traffic-counter#6]
Hi sir,
How change traffic view from barchart to linechart?

**Comment by muhannad0** [comment]
Hello. The project is using Google Charts to draw the charts. They [already support line charts](https://developers.google.com/chart/interactive/docs/gallery/linechart).

You can update these lines to update the chart.
https://github.com/muhannad0/mikrotik-traffic-counter/blob/87f02bd513f23d21f41966ca8dd66f34534e683a/index.php#L52-L54

I'm not actively maintaining this project now since I have moved away from Mikrotik devices at work. So I don't have the necessary equipment to tinker with. So feel free to fork and update it to your liking.
